server:
  port: 6080
  servlet:
   context-path: /api
spring:
  datasource:
    url: jdbc:sqlite:bank.db
    username:
    password:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
logging:
  file: ./logs/tmb-ms.log
  level:
    org.springframework.web: info