server:
  port: 6080
  servlet:
   context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tm_app?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: tm_app
    password: tm_app
  jpa:
    hibernate.ddl-auto: none